global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 1.0
  publish_frequency: 1.0
  width: 6.0
  height: 6.0
  resolution: 0.1
  origin_x: -3.0
  origin_y: -3.0
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    
static_layer:
  map_topic: "/static_map"   # map_server의 정적 맵 토픽
  subscribe_to_updates: true

obstacle_layer:
  observation_sources: laser_scan

laser_scan:
  topic: /scan
  sensor_frame: laser_frame
  data_type: LaserScan
  clearing: true
  marking: true
  obstacle_range: 2.0
  raytrace_range: 2.5

inflation_layer:
  inflation_radius: 0.0
  cost_scaling_factor: 0.0
