local_costmap:
  global_frame: "base_footprint"
  robot_base_frame: "base_link"
  update_frequency: 1.0
  publish_frequency: 1.0
  width: 1.0
  height: 1.0
  resolution: 0.1
  rolling_window: true
  static_map: false
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan
laser_scan:
  topic: /scan
  sensor_frame: laser_frame
  data_type: LaserScan
  clearing: true
  marking: true
  obstacle_range: 0.5
  raytrace_range: 1.0

inflation_layer:
  inflation_radius: 0.0
  cost_scaling_factor: 0.0
